### ISSUE TITLE
super init()

### ISSUE THREAD

**Issue by mendrik** [bfil/es5-class#1]
when having a deep hierarchy and calling this._super.init() in each overwritten init(), the last class causes a "Maximum call stack size exceeded". I'm not quite sure why this happens, but I suspect that if the highest class has no parent, it calls again the class below and then class again.

**Comment by mendrik** [comment]
As a more precise example to reproduce:
var Animal = Class.extend("Animal", {
    init: function() {
        this._super();
    }
})

var Bird = Animal.extend("Bird", {
    init: function() {
        this._super();
    }
})

var Eagle = Bird.extend("Eagle", {
    init: function() {
        this._super();
    }
})

Eagle.create()

**Comment by pocesar** [comment]
@mendrik my version of this module takes care of everything this repo lacks, if you are interested even though the API changed a bit https://github.com/pocesar/ES5-Class
